Moved old pipelines and added debug to main pipeline

diff --git a/.github/workflows/azure-static-web-apps-victorious-ground-01a71db03.yml b/.github/workflows/azure-static-web-apps-victorious-ground-01a71db03.yml
--- a/.github/workflows/azure-static-web-apps-victorious-ground-01a71db03.yml
+++ b/.github/workflows/azure-static-web-apps-victorious-ground-01a71db03.yml
@@ -24,8 +24,17 @@ jobs:
         with:
           dotnet-version: '10.0.x'
 
+
+      - name: .NET Info
+        run: dotnet --info
+
       - name: Publish Blazor App (Release)
         run: dotnet publish DevToolkit/DevToolkit.Web/DevToolkit.Web.csproj -c Release -o DevToolkit/DevToolkit.Web/bin/Release/net10.0/publish
+
+      - name: List Publish Directory
+        run: |
+          echo "Listing contents of publish directory:"
+          ls -l DevToolkit/DevToolkit.Web/bin/Release/net10.0/publish || echo "Publish directory not found"
 
       - name: Build And Deploy
         id: builddeploy
